name: 'Setup Release Environment'
description: 'Prepares environment variables for draft release notes'

inputs:
  base_ref:
    description: 'Base branch ref'
    required: true
  pr_title:
    description: 'Pull request title'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  pr_labels:
    description: 'Pull request labels'
    required: true
  compare_branch:
    description: 'Compare branch ref'
    required: true

outputs:
  version:
    description: 'Release version'
    value: ${{ steps.set-vars.outputs.version }}
  category:
    description: 'Release category'
    value: ${{ steps.set-vars.outputs.category }}
  subcategory:
    description: 'Release subcategory'
    value: ${{ steps.set-vars.outputs.subcategory }}
  content:
    description: 'Release content'
    value: ${{ steps.set-vars.outputs.content }}
  labels:
    description: 'PR labels'
    value: ${{ inputs.pr_labels }}

runs:
  using: "composite"
  steps:
    - id: set-vars
      shell: bash
      run: |
        # Set version
        VERSION=${BASE_REF#RB-}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Debug logging
        echo "Input PR Labels: ${{ inputs.pr_labels }}"
        echo "Checking common labels..."
        echo '${{ inputs.pr_labels }}' | jq 'map(select(startswith("common-")))'
        
        # Determine category with detailed logging
        if echo '${{ inputs.pr_labels }}' | jq -e 'map(select(startswith("common-"))) | length > 0' > /dev/null; then
          echo "Found common- label"
          CATEGORY="COMMON"
        elif echo '${{ inputs.pr_labels }}' | jq -e 'contains(["ntrance_web"])' > /dev/null; then
          echo "Found ntrance_web label"
          CATEGORY="WEB"
        elif echo '${{ inputs.pr_labels }}' | jq -e 'contains(["ntrance_admin"])' > /dev/null; then
          echo "Found ntrance_admin label"
          CATEGORY="ADMIN"
        else
          echo "No matching category labels found, using ETC"
          CATEGORY="ETC"
        fi
        echo "Selected Category: $CATEGORY"
        echo "category=$CATEGORY" >> $GITHUB_OUTPUT
        
        # Determine subcategory with logging
        if [[ "${{ inputs.compare_branch }}" == feat* ]]; then
          SUBCATEGORY="Changes"
        elif [[ "${{ inputs.compare_branch }}" == fix* || "${{ inputs.compare_branch }}" == membersus* || "${{ inputs.compare_branch }}" == jira* ]]; then
          SUBCATEGORY="Bug fixes"
        else
          SUBCATEGORY="etc"
        fi
        echo "Selected Subcategory: $SUBCATEGORY"
        echo "subcategory=$SUBCATEGORY" >> $GITHUB_OUTPUT
        
        # Set content with logging
        CONTENT="- ${{ inputs.pr_title }} (#${{ inputs.pr_number }})"
        echo "Generated Content: $CONTENT"
        echo "content=$CONTENT" >> $GITHUB_OUTPUT
      env:
        BASE_REF: ${{ inputs.base_ref }}