name: 'Setup Release Environment'
description: 'Prepares environment variables for draft release notes'

inputs:
  base_ref:
    description: 'Base branch ref'
    required: true
  pr_title:
    description: 'Pull request title'
    required: true
  pr_number:
    description: 'Pull request number'
    required: true
  pr_labels:
    description: 'Pull request labels'
    required: true
  compare_branch_ref:
    description: 'Compare branch ref'
    required: true

outputs:
  version:
    description: 'Release version'
    value: ${{ steps.set-vars.outputs.version }}
  category:
    description: 'Release category'
    value: ${{ steps.set-vars.outputs.category }}
  subcategory:
    description: 'Release subcategory'
    value: ${{ steps.set-vars.outputs.subcategory }}
  content:
    description: 'Release content'
    value: ${{ steps.set-vars.outputs.content }}
  labels:
    description: 'PR labels'
    value: ${{ inputs.pr_labels }}

runs:
  using: "composite"
  steps:
    - id: set-vars
      shell: bash
      run: |
        # release note version setting
        VERSION=${BASE_REF#RB-}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        
        # Check PR Labels and Set CATEGORY
        if echo '${{ inputs.pr_labels }}' | jq -e 'map(select(startswith("common-"))) | length > 0' > /dev/null; then
          CATEGORY="COMMON"
        elif echo '${{ inputs.pr_labels }}' | jq -e 'contains(["ntrance_web"])' > /dev/null; then
          CATEGORY="WEB"
        elif echo '${{ inputs.pr_labels }}' | jq -e 'contains(["ntrance_admin"])' > /dev/null; then
          CATEGORY="ADMIN"
        else
          CATEGORY="ETC"
        fi
        echo "category=$CATEGORY" >> $GITHUB_OUTPUT
        
        # Check branch name and Set SUBCATEGORY
        if [[ "${{ inputs.compare_branch_ref }}" == feat* ]]; then
          SUBCATEGORY="Changes"
        elif [[ "${{ inputs.compare_branch_ref }}" == fix* || "${{ inputs.compare_branch_ref }}" == bts* || "${{ inputs.compare_branch_ref }}" == jira* ]]; then
          SUBCATEGORY="Bug fixes"
        else
          SUBCATEGORY="etc"
        fi
        echo "subcategory=$SUBCATEGORY" >> $GITHUB_OUTPUT
        
        # Set content
        CONTENT="- ${{ inputs.pr_title }} (#${{ inputs.pr_number }})"
        echo "content=$CONTENT" >> $GITHUB_OUTPUT
      env:
        BASE_REF: ${{ inputs.base_ref }}