name-template: '$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
version-template: '$MAJOR.$MINOR.$PATCH'

template: |
  ## Changes for $RESOLVED_VERSION

  $CHANGES

categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'

change-template: '- $TITLE (#$NUMBER)'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: minor

exclude-labels:
  - 'skip-changelog'

include-labels:
  - '*'

references:
  - main
  - RB-*

exclude-contributors:
  - 'dependabot'

exclude-labels:
  - 'skip-changelog'