name: Auto Release Notes

on:
  pull_request:
    types: [closed]
    branches:
      - 'RB-*'

jobs:
  update-release-notes:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Get branch name
        run: echo "BRANCH=${GITHUB_BASE_REF#RB-}" >> $GITHUB_ENV

      - name: Get PR details
        run: |
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_ENV
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_ENV
          echo "PR_LABELS=${{ toJson(github.event.pull_request.labels.*.name) }}" >> $GITHUB_ENV
          echo "COMPARE_BRANCH=${{ github.event.pull_request.head.ref }}" >> $GITHUB_ENV

      - name: Update or create release notes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          release_id=$(gh release view $BRANCH --json id -q .id 2>/dev/null || echo '')
          
          # Check if PR should be skipped
          if echo "$PR_LABELS" | jq -e 'contains(["skip-release-note"])' > /dev/null; then
            echo "Skipping release note for this PR"
            exit 0
          fi
          
          # Initialize template
          template="# Release $BRANCH

          ## WEB
          ### Changes
          ### Bug fixes
          ### etc

          ## ADMIN
          ### Changes
          ### Bug fixes
          ### etc

          ## COMMON
          ### Changes
          ### Bug fixes
          ### etc

          ## ETC
          "
          
          # Determine category and subcategory
          category="ETC"
          subcategory=""
          
          if echo "$PR_LABELS" | jq -e 'map(select(startswith("common-"))) | length > 0' > /dev/null; then
            category="COMMON"
          elif echo "$PR_LABELS" | jq -e 'contains(["ntrance_web"])' > /dev/null; then
            category="WEB"
          elif echo "$PR_LABELS" | jq -e 'contains(["ntrance_admin"])' > /dev/null; then
            category="ADMIN"
          fi

          if [[ "$COMPARE_BRANCH" == feat* ]]; then
            subcategory="Changes"
          elif [[ "$COMPARE_BRANCH" == fix* || "$COMPARE_BRANCH" == membersus* || "$COMPARE_BRANCH" == jira* ]]; then
            subcategory="Bug fixes"
          else
            subcategory="etc"
          fi
          
          # Prepare new content
          new_content="- $PR_TITLE (#$PR_NUMBER)"
          
          if [ -z "$release_id" ]; then
            echo "$template" > release_notes.md
            if [ "$category" == "ETC" ]; then
              sed -i "s/## ETC/## ETC\n$new_content/" release_notes.md
            else
              sed -i "/## $category/,/## / s/### $subcategory/### $subcategory\n$new_content/" release_notes.md
            fi
            gh release create $BRANCH --draft --title "Release $BRANCH" --notes-file release_notes.md
          else
            gh release view $BRANCH --json body -q .body > release_notes.md
            if [ "$category" == "ETC" ]; then
              sed -i "/## ETC/a $new_content" release_notes.md
            else
              sed -i "/## $category/,/## / s/### $subcategory/### $subcategory\n$new_content/" release_notes.md
            fi
            gh release edit $BRANCH --notes-file release_notes.md
          fi