name: Auto Generate Draft Release Notes

on:
  pull_request:
    types: [closed]
    branches:
      - 'RB-*'

jobs:
  update-release-notes:
    if: ${{ github.event.pull_request.merged == true && !contains(github.event.pull_request.labels.*.name, 'skip-release-note') }}
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_NOTE_PAT }}

      - name: Setup release environment
        id: setup
        uses: ./.github/actions/setup-release
        with:
          base_ref: ${{ github.base_ref }}
          pr_title: ${{ github.event.pull_request.title }}
          pr_number: ${{ github.event.pull_request.number }}
          pr_labels: ${{ toJson(github.event.pull_request.labels.*.name) }}
          compare_branch_ref: ${{ github.event.pull_request.head.ref }}

      - name: Update release notes
        uses: ./.github/actions/update-release-notes
        with:
          version: ${{ steps.setup.outputs.version }}
          category: ${{ steps.setup.outputs.category }}
          subcategory: ${{ steps.setup.outputs.subcategory }}
          content: ${{ steps.setup.outputs.content }}
          github_token: ${{ secrets.RELEASE_NOTE_PAT }}